- name: Configure image data
  ansible.builtin.shell: |
    set -a
    REPO_PATH="/tmp/VCS/github.com/actions/runner-images"
    BUILD_SCRIPTS_PATH="${REPO_PATH}/images/ubuntu/scripts/build"
    HELPER_SCRIPTS="${REPO_PATH}/images/ubuntu/scripts/helpers"
    INSTALLER_SCRIPT_FOLDER="${REPO_PATH}/images/ubuntu/scripts/build"
    DEBIAN_FRONTEND='noninteractive'
    set +a
    
    /bin/bash ${BUILD_SCRIPTS_PATH}/configure-image-data.sh
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true

- name: Configure image data STDOUT
  ansible.builtin.debug:
    msg: "{{ result.stdout_lines }}"

- name: Configure image data STDERR
  when: result.rc != 0
  ansible.builtin.fail:
    msg: "{{ result.stderr_lines }}"

- name: Retrieve IMAGEDATA_FILE
  ansible.builtin.slurp:
    src: "{{ IMAGEDATA_FILE }}"
  register: imagedata

- name: Display IMAGEDATA_FILE
  ansible.builtin.debug:
    msg: "{{ imagedata}}"