- name: Configure image data
  ansible.builtin.shell: |
    set -a
    REPO_PATH="/tmp/VCS/github.com/actions/runner-images"
    BUILD_SCRIPTS_PATH="${REPO_PATH}/images/ubuntu/scripts/build"
    HELPER_SCRIPTS="${REPO_PATH}/images/ubuntu/scripts/helpers"
    INSTALLER_SCRIPT_FOLDER="${REPO_PATH}/images/ubuntu/scripts/build"
    DEBIAN_FRONTEND='noninteractive'
    IMAGE_VERSION=dev
    IMAGEDATA_FILE='/imagegeneration/imagedata.json'
    set +a
    
    /bin/sh "${BUILD_SCRIPTS_PATH}/configure-image-data.sh"
  args:
    executable: /bin/sh
  register: result
  ignore_errors: true

- name: Configure image data STDOUT
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Configure image data STDERR
  when: result.rc != 0
  fail:
    msg: "{{ result.stderr_lines }}"
