- name: configure-apt-sources.sh
  ansible.builtin.shell: |
    set -a
    REPO_PATH="/tmp/VCS/github.com/actions/runner-images"
    BUILD_SCRIPTS_PATH="${REPO_PATH}/images/ubuntu/scripts/build"
    HELPER_SCRIPTS="${REPO_PATH}/images/ubuntu/scripts/helpers"
    INSTALLER_SCRIPT_FOLDER="${REPO_PATH}/images/ubuntu/scripts/build"
    DEBIAN_FRONTEND='noninteractive'
    set +a

    /bin/bash -e "${BUILD_SCRIPTS_PATH}/configure-apt-sources.sh"
  args:
    executable: /bin/bash
  register: result
  ignore_errors: true

- name: configure-apt-sources.sh STDOUT
  debug:
    msg: "{{ result.stdout_lines }}"

- name: configure-apt-sources.sh STDERR
  when: result.rc != 0
  fail:
    msg: "{{ result.stderr_lines }}"