- name: Create image folder
  ansible.builtin.file:
    path: '{{ IMAGE_FOLDER }}'
    state: directory
    mode: '0777'

#- name: Create script folder
#  ansible.builtin.file:
#    path: '{{ INSTALLER_SCRIPT_FOLDER }}'
#    state: directory
#    mode: '0777'