- name: Install git, git-lfs, gh, zstd
  ansible.builtin.shell: |
    set -a
    REPO_PATH="/tmp/VCS/github.com/actions/runner-images"
    BUILD_SCRIPTS_PATH="${REPO_PATH}/images/ubuntu/scripts/build"
    HELPER_SCRIPTS="${REPO_PATH}/images/ubuntu/scripts/helpers"
    INSTALLER_SCRIPT_FOLDER="${REPO_PATH}/images/ubuntu/scripts/build"
    DEBIAN_FRONTEND='noninteractive'
    set +a

    /bin/sh "${BUILD_SCRIPTS_PATH}install-git.sh"
    /bin/sh "${BUILD_SCRIPTS_PATH}install-git-lfs.sh"
    /bin/sh "${BUILD_SCRIPTS_PATH}install-github-cli.sh"
    /bin/sh "${BUILD_SCRIPTS_PATH}install-zstd.sh"
  args:
    executable: /bin/sh
  register: result
  ignore_errors: true

- name: Install git, git-lfs, gh, zstd STDOUT
  debug:
    msg: "{{ result.stdout_lines }}"

- name: Install git, git-lfs, gh, zstd STDERR
  when: result.rc != 0
  fail:
    msg: "{{ result.stderr_lines }}"