- import_tasks: pkgx.yaml 
  tags: install

- import_tasks: repo_clone.yaml
  tags: install

- import_tasks: repo_scripts.yaml
  tags: install

- import_tasks: configure_image_data.yaml
  tags: install

- import_tasks: configure_environment.yaml
  tags: install

- import_tasks: configure_limits.yaml
  tags: install

- import_tasks: install_clang.yaml
  tags: install

- import_tasks: install_ruby.yaml
  tags: install

- import_tasks: install_git.yaml
  tags: install