- ansible.builtin.import_tasks: create_folders.yaml
  tags: install
- ansible.builtin.import_tasks: repo_clone.yaml
  tags: install
- ansible.builtin.import_tasks: configure-apt-mock.yaml
  tags: install
- ansible.builtin.import_tasks: configure-apt.yaml
  tags: install
- ansible.builtin.import_tasks: configure-apt-sources.yaml
  tags: install
- ansible.builtin.import_tasks: install-ms-repos.yaml
  tags: install

- ansible.builtin.import_tasks: install-toolset-config.yaml
  tags: install

- ansible.builtin.import_tasks: configure_image_data.yaml
  tags: install

- ansible.builtin.import_tasks: configure_environment.yaml
  tags: install

- ansible.builtin.import_tasks: install_apt_vital.yaml
  tags: install

- ansible.builtin.import_tasks: configure-limits.yaml
  tags: install

#- ansible.builtin.import_tasks: install_clang.yaml
#  tags: install

#- ansible.builtin.import_tasks: install_ruby.yaml
#  tags: install

#- ansible.builtin.import_tasks: install_git.yaml
#  tags: install

#- ansible.builtin.import_tasks: install_docker.yaml
#  tags: install

- ansible.builtin.import_tasks: pkgx.yaml 
  tags: install

- ansible.builtin.import_tasks: install-terraform.yaml
  tags: install

- ansible.builtin.import_tasks: install-packer.yaml
  tags: install