- name: Install clang
  ansible.builtin.shell: |
    /bin/sh /tmp/VCS/github.com/actions/runner-images/images/ubuntu/scripts/build/install-clang.sh
  args:
    executable: /bin/sh
  register: out

- name: print output
  debug:
    msg: "{{ out.stdout }}"