- name: Install clang
  ansible.builtin.shell: |
    set -a
    #HELPER_SCRIPTS=
    set +a
    /bin/sh /tmp/VCS/github.com/actions/runner-images/images/ubuntu/scripts/build/install-clang.sh
  args:
    executable: /bin/sh
  register: result
  ignore_errors: true

- name: print output
  debug:
    msg: "{{ result.stdout }}"

- name: fail
  when: result.rc != 0
  fail:
    msg: "{{ result.stderr_lines }}"
